title: "Prof. Sujit Chaudhari"
description: "Professor of Computer Science | AI, Cloud Computing, NLP"
baseurl: ""
url: "https://yourusername.github.io/professor-profile"

# Navigation Menu
nav:
  - name: "Home"
    link: /
  - name: "About"
    link: /about
  - name: "Research"
    link: /research
  - name: "Publications"
    link: /publications
  - name: "Contact"
    link: /contact
